Update export.yaml

diff --git a/.github/workflows/export.yaml b/.github/workflows/export.yaml
--- a/.github/workflows/export.yaml
+++ b/.github/workflows/export.yaml
@@ -37,9 +37,12 @@ jobs:
 
     - name: Upload Zip
       run: |
-        if curl --data-binary "@build.zip" \
+        RESPONSE=$(curl --data-binary "@build.zip" \
             "${{secrets.uploadUrl}}?godot_id=${{env.GODOT_ASSET_ID}}&xodot_id=${{env.XODOT_ASSET_ID}}&version=${{ github.ref_name }}" \
-            -H "apiKey: ${{secrets.apiKey}}" \
-        then echo "SUCCESS" \
-        else echo "FAILURE" \
+            -H "apiKey: ${{secrets.apiKey}}")
+        if [ $? -eq 0 ]; then
+          echo "SUCCESS"
+        else
+          echo "FAILURE"
+          exit 1
         fi
